name=Auto485
version=1.0.0
author=Michael Adams
maintainer=Michael Adams
sentence=Helper library for RS485 communication
paragraph=Auto485 is a small helper library that takes some of the tedium out of RS485 communication. It automatically handles the DE/RE pin toggling for half-duplex RS485 transceivers.
category=Communication
url=https://github.com/madleech/Auto485
architectures=*
includes=Auto485.h
